### ISSUE TITLE
Database is locked issue on Rinkeby only

### ISSUE THREAD

**Issue by edisinovcic** [sourcifyeth/go-ethereum#1]
When running this fork on logContractCode branch with parameters:
./geth --rinkeby --syncmode "full".

```
panic: database is locked

goroutine 238249 [running]:
github.com/ethereum/go-ethereum/core/vm.storeCode(0xc0026ff140, 0x2a, 0xc02557a3c0, 0x1d9, 0x1d9, 0xc00ccd7720, 0x42)
        github.com/ethereum/go-ethereum/core/vm/evm.go:436 +0x265
github.com/ethereum/go-ethereum/core/vm.(*EVM).create(0xc00727aa80, 0x1586380, 0xc007bb1b60, 0xc0005bf8b8, 0x467234, 0xc011e1d060, 0xec62f967ad86383c, 0xfb918cdc1c051cbd, 0xc0cf3da7a2, 0xc013e300a0, ...)
        github.com/ethereum/go-ethereum/core/vm/evm.go:490 +0xba5
github.com/ethereum/go-ethereum/core/vm.(*EVM).Create(0xc00727aa80, 0x1586380, 0xc007bb1b60, 0xc02557a3c0, 0x1d9, 0x1d9, 0x467234, 0xc011e1d060, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/core/vm/evm.go:520 +0x1ed
github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc024bcfd50, 0x15ac880, 0xc0130cff20, 0xc005b682c0)
        github.com/ethereum/go-ethereum/core/state_transition.go:256 +0x6ff
github.com/ethereum/go-ethereum/core.ApplyMessage(0xc00727aa80, 0x15ac880, 0xc0130cff20, 0xc005b682c0, 0x191543a60d5fd24, 0xbafabd61, 0xc013e30000)
        github.com/ethereum/go-ethereum/core/state_transition.go:164 +0x57
github.com/ethereum/go-ethereum/core.precacheTransaction(0x1c499e0, 0x1591f00, 0xc0008ec000, 0x0, 0xc005b682c0, 0xc03a3f82c0, 0xc00bfe8000, 0xc007f6b9e0, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/core/state_prefetcher.go:92 +0x2eb
github.com/ethereum/go-ethereum/core.(*statePrefetcher).Prefetch(0xc00089a340, 0xc05c1c3ef0, 0xc03a3f82c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/core/state_prefetcher.go:65 +0x354
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain.func2(0xc0008ec000, 0xc027d5fee0, 0xbfec554ad134f75c, 0x4049920946, 0x1eb11a0, 0xc05c1c3ef0, 0xc03a3f82c0, 0xc027d5fee0)
        github.com/ethereum/go-ethereum/core/blockchain.go:1803 +0xda
created by github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain
        github.com/ethereum/go-ethereum/core/blockchain.go:1802 +0x2b33
```

**Comment by edisinovcic** [comment]
Should be solved by: https://github.com/sourcifyeth/go-ethereum/pull/2 @Jakic007 please take a look if this version works properly and merge afterwards.
